apiVersion: v1
kind: Service
metadata:
  name: gemma-host
  namespace: jmlc
spec:
  type: ExternalName
  externalName: host.minikube.internal
  ports:
    - name: http
      port: 8000
      targetPort: 8000
